#!/usr/bin/env python
from argparse import ArgumentParser

# 1 get the parser
parser = ArgumentParser(
    description="Greeting utility"
)

# 2 give arguments
parser.add_argument(
    "--name",
    type=str,
    help="Name of the user",
    required=True
    # default="admin"
)

parser.add_argument(
    "--role",
    type=str,
    help="Role of the user",
    required=True
    # default="bench"
)

# name = input("Please enter your name : ")
# role = input("Please enter your role : ")

# 3 parse the arguments
args = parser.parse_args()
# print(args)

name = args.name 
role = args.role 

if name and role:
    print(f"Hello {name}, welcome to the {role} team!")
else:
    print("need name and role values")



# file run
# python greeting.py --name firoz --role dba


_ = """
#!/bin/bash -> bash

python greeting.py --name firoz --role dba

python greeting.py \
    --name firoz \
    --role dba

r - read
w - write
x - execute

ft  u    g    o
--  --   --   --
d   rwx  r-x  r-x  
-   rw-  r--  r--  greet.py
-   rwx  r-x  r-x  tmp.txt

/greet.py --name firoz --role dba
/greet.py --help

greet --name firoz --role dba

copy script
cp greet /bin/
use sudo when permission denied

create a link/shortcut
ln -s src dest/name

greet --name firoz --role dba

AWS Sagamaker -> DS/ML/AI
Training Instances -> python code and pass these arguemnts during run time

cron jobs
"""


# class Namespace:
#     name ='firoz'
#     role = 'dba'

# namespace = Namespace()
# namespace.name